name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
          outputs: |
  dist/github-contribution-grid-snake.svg?color_snake=%2300ffff&color_dots=%23161b22%2330134d%235b21b6%238a2be2%23c084fc
  dist/github-contribution-grid-snake-dark.svg?color_snake=%2300ffff&color_dots=%230b0b14%2330134d%237b2cbf%23a855f7%23e879f9f

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
